branch-defaults:
  '1':
    environment: Schedule-env
  main:
    environment: Schedule-env
environment-defaults:
  Schedule-env:
    branch: null
    repository: null
global:
  application_name: Schedule
  branch: '1'
  default_ec2_keyname: Schedule_App_Key
  default_platform: PHP 7.4 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
